title = "ETEPLUS"
description = "ETEPLUS is a front-end web developer. 👻"
# The URL the site will be built for
base_url = "https://eteplus.com"

minify_html = false

build_search_index = false

generate_feed = true

taxonomies = [
  { name = "tags", paginate_by = 4, feed = true }
]

[markdown]
highlight_code = true

highlight_theme = "one-dark"

render_emoji = true

smart_punctuation = true

external_links_target_blank = true

external_links_no_follow = true

external_links_no_referrer = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
author = "eteplus"
github = "https://github.com/eteplus"
twitter = "eteplus"
email = "eteplus@outlook.com"

language_code = "zh-CN"

menus = [
  { name = "Home", url = "/" },
  { name = "Posts", url = "/posts" },
  { name = "Archives", url = "/archives"},
  { name = "Tags", url = "/tags" },
  { name = "About", url = "/about" }
]

google_analytics_token = "G-9GEVV08W03"

[extra.seo]
image =""
audio = ""
# video resoure
videos = []
locale = 'zh-CN'
